server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-75-230-253.eu-west-1.compute.amazonaws.com:5432/d8dtt6craifcb9
    username: tcohgrcvwbfxrv
    password: 9a40bc209bd02fee594ac9d97faadcdb28e6b498c7754322174eaf429a394f82

#    postgres://tcohgrcvwbfxrv:9a40bc209bd02fee594ac9d97faadcdb28e6b498c7754322174eaf429a394f82@ec2-54-75-230-253.eu-west-1.compute.amazonaws.com:5432/d8dtt6craifcb9